# Generated by Django 5.2 on 2025-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('credit_card', 'Carte de crédit')], default='cash_on_delivery', max_length=20),
        ),
    ]
