# Generated by Django 5.2 on 2025-06-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0004_twofactortoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorToken',
        ),
    ]
